#!/bin/bash
## My first script

echo "Cat to combo and then compile to create executable called combo"

DIR1=/home/ec2-user/migit
DIR2=/vol/migit

#cp $DIR1/*     $DIR2/.
#cp $DIR1/agres.txt     $DIR2/.
#cp $DIR1/cohabinit.txt $DIR2/.
#cp $DIR1/cohabPSID.txt $DIR2/.
#cp familymigPSID.txt $DIR2/.
#cp bestpar121416.txt $DIR2/.

echo "I am here !"

echo "I am here 2!"

cd $DIR1

echo "I am here 3!"
cat nrtype.f90 nrutil.f90 nr.f90 pNelder_mead_cluster040615.f90 indexx.f90 sort2.f90 locate.f90 gauher.f90 alib.f90 mig_params.f90 mig_share.f90 mig_yaz.f90 mig_sol.f90 mig_mom.f90 mig_objf.f90 mig_main.f90 > $DIR1/program.f90
#cat nrtype.f90 nrutil.f90 nr.f90 ran_state.f90 ran2.f90 testran.f90  > $DIR1/program.f90 
#cat testran2.f90 > $DIR1/program.f90

echo "I am here 4!"


/usr/lib64/mpich/bin/mpif90 $DIR1/program.f90 -ffree-line-length-none -o $DIR1/mig.x
#/usr/lib64/mpich/bin/mpif90 $DIR1/program.f90 -ffree-line-length-none -fcheck=all -o $DIR1/mig.x
#/usr/lib64/mpich/bin/mpif90 $DIR1/program.f90 -ffree-line-length-none -O0 -fbounds-check -fwrapv -fno-strict-overflow -o $DIR1/mig.x

echo "Done"

